Add Index file
sameedmohsin28/Hello-World pull request #1
Opened 2023-01-12 23:16 UTC by sameedmohsin28

2023-01-13 00:57 UTC, joskalenda requested changes
Hi @sameedmohsin28 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌

> You have submitted a project, that no pull request summary and failed linters, kindly update these and resubmit your work

<img src="https://media4.giphy.com/media/uqMQsE4HKYvfnjhIRQ/giphy.gif"/>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

-----
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._ 🟢

2023-01-13 21:12 UTC, zieeco requested changes
Hi @sameedmohsin28 ,


Great job with the `Hello Microverse` project! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice project setup. ✔️
- Fair PR description. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 21:12 UTC, zieeco commented on README.md
> +You do not need any pre requisites nor any instructions for this project. This is a basic project to get us started with html, css, git, GitHub, and linters.
- Hey, great job with this project so far, I admire your energy, however, the purpose of this project is to help you get familiar with setting up a professional GitHub repository and get comfortable in doing them repetitively
   - Let's improve our readme by using this [template](https://github.com/microverseinc/readme-template) but you should customize it to suit this current project's needs. 
   - Replace all the placeholder text as they're there meant to guide on how to add some content in the readme
   > Follow the template closely to update them with your personal content but maintain its structure and format.

2023-01-13 21:12 UTC, zieeco commented on test.md
> +This file should be ignored by git
- As this is clearly stated that `I should be ignored by git`, kindly add this file in the `.gitignore` file.

2023-01-13 21:12 UTC, zieeco commented on .gitignore
> +node_modules/
- Add `test.md` so it would be ignored by git

2023-01-13 23:06 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @sameedmohsin28, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ PR descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 23:06 UTC, abdulhamiid commented on README.md
> +I would like to thank https://github.com/matee-safi, https://github.com/mpa-mxiang, https://github.com/baezluise for their support.
As requested by the previous reviewer and [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) please kindly open the link [MICROVERSE readme template](https://github.com/microverseinc/readme-template) and customize it to your project ☺

Kindly replace all the placeholder text as they're there meant to guide on how to add some content in the readme 👍

2023-01-13 23:06 UTC, abdulhamiid commented on .gitignore
> +test.md
The purpose of gitignore files is to ensure that specific files not tracked by Git remain untracked, which means that test.md file should not be present on your GitHub repository please kindly remove it.

👇 
![image](https://user-images.githubusercontent.com/78251927/212433984-3a6b70d4-68f2-4ad7-b5e7-7448eec840a9.png)

2023-01-13 23:15 UTC, abdulhamiid commented
You will have to remove the `test.md` file manually from your GitHub repository

So subsequent time, when you push any changes to GitHub, `.gitignore` file will ensure that `test.md` file is ignored and not pushed to the remote repository.

2023-01-14 20:37 UTC, NduatiKagiri approved these changes
Hi @sameedmohsin28 ,

# APPROVED 💯  

Good job making the requested changes. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![ea0cb5a48e3337523ffe8d60f177879d](https://user-images.githubusercontent.com/87394385/212495673-2043f79b-ddfe-4ef9-8286-84ed89e9d080.gif)

## Highlights ✔️ 
✅ GitHub Flow observed
✅ No Linters errors

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 20:01 UTC, merged